package org.dimas4ek.wrapper.types;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum GatewayEvent {
    HELLO("Defines the heartbeat interval"),
    READY("Contains the initial state information"),
    RESUMED("Response to Resume"),
    RECONNECT("Server is going away, client should reconnect to gateway and resume"),
    INVALID_SESSION("Failure response to Identify or Resume or invalid active session"),
    APPLICATION_COMMAND_PERMISSIONS_UPDATE("Application command permission was updated"),
    AUTO_MODERATION_RULE_CREATE("Auto Moderation rule was created"),
    AUTO_MODERATION_RULE_UPDATE("Auto Moderation rule was updated"),
    AUTO_MODERATION_RULE_DELETE("Auto Moderation rule was deleted"),
    AUTO_MODERATION_ACTION_EXECUTION("Auto Moderation rule was triggered and an action was executed (e.g. a message was blocked)"),
    CHANNEL_CREATE("New guild channel created"),
    CHANNEL_UPDATE("Channel was updated"),
    CHANNEL_DELETE("Channel was deleted"),
    CHANNEL_PINS_UPDATE("Message was pinned or unpinned"),
    THREAD_CREATE("Thread created, also sent when being added to a private thread"),
    THREAD_UPDATE("Thread was updated"),
    THREAD_DELETE("Thread was deleted"),
    THREAD_LIST_SYNC("Sent when gaining access to a channel, contains all active threads in that channel"),
    THREAD_MEMBER_UPDATE("Thread member for the current user was updated"),
    THREAD_MEMBERS_UPDATE("Some user(s) were added to or removed from a thread"),
    ENTITLEMENT_CREATE("Entitlement was created"),
    ENTITLEMENT_UPDATE("Entitlement was updated or renewed"),
    ENTITLEMENT_DELETE("Entitlement was deleted"),
    GUILD_CREATE("Lazy-load for unavailable guild, guild became available, or user joined a new guild"),
    GUILD_UPDATE("Guild was updated"),
    GUILD_DELETE("Guild became unavailable, or user left/was removed from a guild"),
    GUILD_AUDIT_LOG_ENTRY_CREATE("A guild audit log entry was created"),
    GUILD_BAN_ADD("User was banned from a guild"),
    GUILD_BAN_REMOVE("User was unbanned from a guild"),
    GUILD_EMOJIS_UPDATE("Guild emojis were updated"),
    GUILD_STICKERS_UPDATE("Guild stickers were updated"),
    GUILD_INTEGRATIONS_UPDATE("Guild integration was updated"),
    GUILD_MEMBER_ADD("New user joined a guild"),
    GUILD_MEMBER_REMOVE("User was removed from a guild"),
    GUILD_MEMBER_UPDATE("Guild member was updated"),
    GUILD_MEMBERS_CHUNK("Response to Request Guild Members"),
    GUILD_ROLE_CREATE("Guild role was created"),
    GUILD_ROLE_UPDATE("Guild role was updated"),
    GUILD_ROLE_DELETE("Guild role was deleted"),
    GUILD_SCHEDULED_EVENT_CREATE("Guild scheduled event was created"),
    GUILD_SCHEDULED_EVENT_UPDATE("Guild scheduled event was updated"),
    GUILD_SCHEDULED_EVENT_DELETE("Guild scheduled event was deleted"),
    GUILD_SCHEDULED_EVENT_USER_ADD("User subscribed to a guild scheduled event"),
    GUILD_SCHEDULED_EVENT_USER_REMOVE("User unsubscribed from a guild scheduled event"),
    INTEGRATION_CREATE("Guild integration was created"),
    INTEGRATION_UPDATE("Guild integration was updated"),
    INTEGRATION_DELETE("Guild integration was deleted"),
    INTERACTION_CREATE("User used an interaction, such as an Application Command"),
    INVITE_CREATE("Invite to a channel was created"),
    INVITE_DELETE("Invite to a channel was deleted"),
    MESSAGE_CREATE("Message was created"),
    MESSAGE_UPDATE("Message was edited"),
    MESSAGE_DELETE("Message was deleted"),
    MESSAGE_DELETE_BULK("Multiple messages were deleted at once"),
    MESSAGE_REACTION_ADD("User reacted to a message"),
    MESSAGE_REACTION_REMOVE("User removed a reaction from a message"),
    MESSAGE_REACTION_REMOVE_ALL("All reactions were explicitly removed from a message"),
    MESSAGE_REACTION_REMOVE_EMOJI("All reactions for a given emoji were explicitly removed from a message"),
    PRESENCE_UPDATE("User was updated"),
    STAGE_INSTANCE_CREATE("Stage instance was created"),
    STAGE_INSTANCE_UPDATE("Stage instance was updated"),
    STAGE_INSTANCE_DELETE("Stage instance was deleted or closed"),
    TYPING_START("User started typing in a channel"),
    USER_UPDATE("Properties about the user changed"),
    VOICE_STATE_UPDATE("Someone joined, left, or moved a voice channel"),
    VOICE_SERVER_UPDATE("Guild's voice server was updated"),
    WEBHOOKS_UPDATE("Guild channel webhook was created, update, or deleted");

    private final String description;
}